version: '2.6'
services:
  cooking-recipes-api:
    image: cooking-recipes-api-image
    ports:
      - 9898:9898
    environment:
      - JWT_SECRET_TOKEN=fd14403498a9db4dc904dbb403c44dca5cd5a8dd94377f6badf9dcb95b10566ec2f3cb1e66e940d2a9d02666b30e5f18
      - DATABASE_NAME=cooking_recipes
      - DATABASE_HOST=172.17.0.1
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=AjboyIan_321
    volumes:
      - ./:/app